### PR TITLE
Fix has_many though associations when the through association is singular

### PR DESCRIPTION
**Pull request by pi-plus-45x23**
Attempting to reify a `has_many through:` association throws an error when the `through:` association is not `has_many`.

Suppose we have these associations defined:
```ruby
class Post < ActiveRecord::Base
  has_one :content
  has_many :content_blocks, through: :content
end
```
Executing
```ruby
post.versions.last.reify(has_many: true)
```
raises `NoMethodError` [here](https://github.com/westonganger/paper_trail-association_tracking/blob/d8db2791154097f9c97759eff84f29d74c7f79c1/lib/paper_trail_association_tracking/reifiers/has_many_through.rb#L71) if `post.content` is nil and [here](https://github.com/westonganger/paper_trail-association_tracking/blob/d8db2791154097f9c97759eff84f29d74c7f79c1/lib/paper_trail_association_tracking/reifiers/has_many_through.rb#L45) otherwise.

Wrapping the through association in an Array will fix the error. However, the given example will still produce incorrect results because we aren't reifying the `content` association with `has_one: true`. Thus, the HMT association should implicitly reify the through association regardless of the options given to `reify`.

### CODE REVIEW

**Comment by westonganger** [comment]
Merged. Thanks for your contribution!

**Comment by Jonwheeler** [comment]
Do we think there will be a release of the gem including these changes?

**Comment by westonganger** [comment]
v2.3.0 has now been released which contains this change.

**Comment by Jonwheeler** [comment]
Thanks so much! Appreciate the work on this project.

**Pull request merged**
