### PR TITLE
Fix for PT issue #594

### PR DESCRIPTION
**Pull request by lorint**
Transitioning away from using base_class in order to support versioned sub-classes that utilise STI.  The other half of this fix is in [PR #1108](https://github.com/paper-trail-gem/paper_trail/pull/1108) in PaperTrail.

### CODE REVIEW

**Comment by westonganger** [comment]
@Iorint now that the PT core fix got merged. Could you please revisit this PR and update as required. Thanks

**Comment by lorint** [comment]
> Could you please revisit this PR and update as required. Thanks

Certainly.  Will have some spare cycles later today to encapsulate the approach we've taken for has_many and has_many_through.  Later in the week can do the belongs_to, and then finalise the other two next week.

Stay tuned :)

**Comment by jaredbeck** [comment]
https://github.com/paper-trail-gem/paper_trail/pull/1108 didn't work out. Instead, we'll add an optional column `item_subtype` to our `versions` table(s), per https://github.com/paper-trail-gem/paper_trail/pull/1143

The addition of this column will be mentioned under the "Fixed" section of the PT 10.0.0 changelog, and (for lack of a better place) users will be directed to this PR for further information about PT-AT's adoption of this new column.

@lorint, Sean, and I believe that PT-AT can adopt this column and fix https://github.com/paper-trail-gem/paper_trail/issues/594 with changes like the following:

```diff
# paper_trail_association_tracking/reifiers/has_one.rb
# def load_versions(assoc, model, transaction_id, version_at, base_class_name)
            where("#{version_table_name}.item_type = ?", base_class_name).
+           where("#{version_table_name}.item_subtype = ?", assoc.class_name).
            where("created_at >= ? OR transaction_id = ?", version_at, transaction_id).
```

**Comment by westonganger** [comment]
Hey @lorint just checking in. Any chance to revisit this PR and get it up to date?

**Comment by westonganger** [comment]
Closing due to inactivity.

**Pull request closed without merging**
